name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Display pwd
        run: echo $PWD
        shell: bash

      - name: Display GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE
        shell: bash
        
      - name: Clean temp directory
        run: rm -rf *
        working-directory: ./temp

      - name: make
        shell: bash
        run: make

      - name: copy hi to temp dir
        run: cp hi ../temp/.
        shell: bash

      - name: Display content GITHUB_WORKSPACE
        run: ls -al $GITHUB_WORKSPACE
        shell: bash

      - name: make install
        run: make install
