name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Display pwd
      run: echo $PWD
      shell: bash
          
    - name: Display workin_directory
      run: echo $WORKING_DIRECTORY
      shell: bash
      
    - name: make
      run: make

    - name: make install
      run: make install
