name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Clean temp directory
      run: rm -rf *
      working-directory: ~/helloc/temp
          
    - uses: actions/checkout@v2
    - name: make
      run: make
      working-directory: ./temp
    - name: make install
      run: make install
