name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Display pwd
      run: echo $PWD
      shell: bash
          
    - uses: actions/checkout@v2
    - name: make
      run: make
      working-directory: ..
    - name: make install
      run: make install
